# Generated by Django 4.2.11 on 2024-05-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(choices=[('youtube', 'Youtube'), ('facebook', 'Facebook'), ('tiktok', 'Tiktok'), ('web', 'Web')], max_length=200)),
                ('Engaged', models.CharField(max_length=200)),
                ('Reach', models.CharField(max_length=200)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markting_campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=40)),
                ('product_size', models.CharField(choices=[('xl', 'XL'), ('m', 'M'), ('xxl', 'XXL'), ('xs', 'XS'), ('s', 'S'), ('l', 'L')], max_length=250)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.marketing')),
                ('cus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('ordered_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crm_user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=260)),
                ('category', models.CharField(choices=[('women', 'Women'), ('mens', 'Mens'), ('girls', 'Girls'), ('boys', 'Boys'), ('children', 'Children')], max_length=20)),
                ('Sub_category', models.CharField(blank=True, max_length=20)),
                ('Style', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('Qunatity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('product_pic', models.ImageField(upload_to='product_pic')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='crm.crm_user')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='crm.order_item', to='crm.product'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='campaign_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.markting_campaign'),
        ),
    ]
